---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: hummingbird-clone-secret-store
  namespace: hummingbird-clone
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hummingbird-clone-secrets-external
  namespace: hummingbird-clone
spec:
  secretStoreRef:
    name: hummingbird-clone-secret-store
    kind: SecretStore
  target:
    name: hummingbird-clone-secrets  # the name of the k8s secret resource that is created
  data:
    - secretKey: mongo-password
      remoteRef:
        key: /latest0/su0/hummingbird-clone/hummingbird-clone-latest0-su0-2023-09-25
