---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spool-pvc
  namespace: hummingbird-clone
spec:
  storageClassName: ebs-csi-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
