---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hummingbird-clone
  name: configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: hummingbird-clone
subjects:
  - kind: ServiceAccount
    name: eso-sa
    namespace: hummingbird-clone
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
